import { CategoryId, MenuCategoryData } from './types';

export const PHONE_NUMBER = "9928334610";

// Base Images from FTCDN (Adobe Stock)
const IMG_ROTI = "https://as2.ftcdn.net/v2/jpg/02/51/50/59/1000_F_251505961_SmbDfvUMOSJaAEBHFfFJRAqitSSKvhCE.jpg";
const IMG_PARATHA_BASE = "https://t3.ftcdn.net/jpg/01/85/22/88/240_F_185228807_ar8L0kwF1zzRxPfJWbGemtQcsLa6ZD2z.jpg";

export const MENU_DATA: MenuCategoryData[] = [
  {
    id: CategoryId.PARATHAS,
    label: "Parathas",
    items: [
      {
        id: 'p0',
        name: "Roti",
        hindiName: "रोटी",
        description: "Freshly made whole wheat flatbread.",
        price: 15,
        image: IMG_ROTI,
        isVeg: true,
        ingredients: ["Whole Wheat Flour", "Water"],
      },
      {
        id: 'p1',
        name: "Plain Paratha",
        hindiName: "सादा पराठा",
        description: "Classic layered paratha cooked with ghee.",
        price: 50,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Wheat Flour", "Ghee", "Salt"],
      },
      {
        id: 'p2',
        name: "Jeera Masala",
        hindiName: "जीरा मसाला",
        description: "Spiced paratha infused with cumin seeds.",
        price: 60,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Cumin", "Spices", "Wheat Flour", "Butter"],
      },
      {
        id: 'p3',
        name: "Sweet Paratha",
        hindiName: "मीठा पराठा",
        description: "A delightful paratha with sugar or jaggery filling.",
        price: 60,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Sugar/Jaggery", "Cardamom", "Ghee", "Wheat Flour"],
      },
      {
        id: 'p4',
        name: "Onion Paratha",
        hindiName: "प्याज़ पराठा",
        description: "Stuffed with finely chopped spicy onions.",
        price: 90,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Onion", "Green Chili", "Coriander", "Spices"],
      },
      {
        id: 'p5',
        name: "Methi Paratha",
        hindiName: "मेथी पराठा",
        description: "Healthy fenugreek leaves kneaded into dough.",
        price: 90,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Methi Leaves", "Wheat Flour", "Spices", "Oil"],
      },
      {
        id: 'p6',
        name: "Aloo Paratha",
        hindiName: "आलू पराठा",
        description: "The classic favorite stuffed with spiced potatoes.",
        price: 90,
        image: IMG_PARATHA_BASE,
        isPopular: true,
        isVeg: true,
        ingredients: ["Potato", "Green Chili", "Ginger", "Coriander"],
      },
      {
        id: 'p7',
        name: "Gobhi Paratha",
        hindiName: "गोभी पराठा",
        description: "Stuffed with grated spiced cauliflower.",
        price: 100,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Cauliflower", "Ginger", "Green Chili", "Spices"],
      },
      {
        id: 'p8',
        name: "Mix Veg Paratha",
        hindiName: "मिक्स वेज पराठा",
        description: "A nutritious blend of mixed vegetables and spices.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Carrot", "Peas", "Beans", "Potato", "Spices"],
      },
      {
        id: 'p9',
        name: "Moong Dal Paratha",
        hindiName: "मूंग दाल पराठा",
        description: "Protein-packed paratha stuffed with seasoned yellow lentils.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Moong Dal", "Fennel Seeds", "Heeng", "Spices"],
      },
      {
        id: 'p10',
        name: "Garlic Paratha",
        hindiName: "लहसुन पराठा",
        description: "Flavorful paratha with a kick of fresh garlic.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Garlic", "Butter", "Chili Flakes", "Coriander"],
      },
      {
        id: 'p11',
        name: "Green Peas Paratha",
        hindiName: "मटर पराठा",
        description: "Sweet and spicy mashed green peas filling.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Green Peas", "Ginger", "Green Chili", "Cumin"],
      },
      {
        id: 'p12',
        name: "Satu / Masala Paratha",
        hindiName: "सत्तू/मसाला पराठा",
        description: "Traditional roasted gram flour filling with tangy spices.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Sattu", "Pickle Spices", "Onion", "Mustard Oil"],
      },
      {
        id: 'p13',
        name: "Namkeen Sev Paratha",
        hindiName: "नमकीन सेव पराठा",
        description: "Crunchy sev filling for a unique texture and taste.",
        price: 110,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Sev", "Spices", "Onion", "Coriander"],
      },
      {
        id: 'p14',
        name: "Paneer Paratha",
        hindiName: "पनीर पराठा",
        description: "Rich cottage cheese filling with aromatic spices.",
        price: 120,
        image: IMG_PARATHA_BASE,
        isPopular: true,
        isVeg: true,
        ingredients: ["Paneer", "Garam Masala", "Butter", "Wheat Flour"],
      },
      {
        id: 'p15',
        name: "Cheese Paratha",
        hindiName: "चीज़ पराठा",
        description: "Loaded with gooey cheese for cheese lovers.",
        price: 145,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Processed Cheese", "Mozzarella", "Herbs", "Butter"],
      },
      {
        id: 'p16',
        name: "Kokin Paratha",
        hindiName: "कोकिन पराठा",
        description: "Special Konkan style paratha with unique spices.",
        price: 145,
        image: IMG_PARATHA_BASE,
        isVeg: true,
        ingredients: ["Coconut", "Special Masala", "Rice Flour", "Ghee"],
      },
      {
        id: 'p17',
        name: "Shahi Paratha",
        hindiName: "शाही पराठा",
        description: "A royal treat with rich dry fruits and paneer.",
        price: 160,
        image: IMG_PARATHA_BASE,
        isPopular: true,
        isVeg: true,
        ingredients: ["Cashews", "Raisins", "Paneer", "Cream", "Saffron"],
      },
    ]
  },
  {
    id: CategoryId.THALIS,
    label: "Thalis",
    items: [
      {
        id: 't1',
        name: "Maharaja Thali",
        hindiName: "महाराजा थाली",
        description: "A royal feast with 2 parathas, 3 sabjis, dal, rice, sweet, and lassi.",
        price: 350,
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
        isPopular: true,
        isVeg: true,
        ingredients: ["Roti", "Paneer Sabji", "Dal Fry", "Jeera Rice", "Gulab Jamun"],
      },
      {
        id: 't2',
        name: "Mini Thali",
        hindiName: "मिनी थाली",
        description: "Perfect for a quick lunch. 1 paratha, sabji, dal, and rice.",
        price: 220,
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
        isVeg: true,
        ingredients: ["Paratha", "Seasonal Sabji", "Dal", "Rice", "Pickle"],
      }
    ]
  },
  {
    id: CategoryId.SABJI,
    label: "Sabji",
    items: [
      {
        id: 's1',
        name: "Paneer Butter Masala",
        description: "Cottage cheese in rich tomato gravy.",
        price: 240,
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80",
        isVeg: true,
        ingredients: ["Paneer", "Tomato", "Cashew Paste", "Cream", "Butter"],
      },
      {
        id: 's2',
        name: "Veg Kolhapuri",
        description: "Spicy mixed vegetable curry.",
        price: 200,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNx4G7zJIl2islD7CsxIrEWwiBj3TULwEnlQ&s",
        isSpicy: true,
        isVeg: true,
        ingredients: ["Mixed Vegetables", "Kolhapuri Masala", "Coconut", "Red Chili"],
      }
    ]
  },
  {
    id: CategoryId.RICE,
    label: "Rice",
    items: [
      {
        id: 'r1',
        name: "Jeera Rice",
        description: "Basmati rice tempered with cumin seeds.",
        price: 140,
        image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/12/jeera-rice-recipe.webp",
        isVeg: true,
        ingredients: ["Basmati Rice", "Cumin Seeds", "Ghee", "Coriander"],
      },
      {
        id: 'r2',
        name: "Dal Khichdi",
        description: "Comfort food made with rice and lentils.",
        price: 180,
        image: "https://i.pinimg.com/736x/70/2a/98/702a9834b4ef71c32d1cb8fef8b0a5ba.jpg",
        isVeg: true,
        ingredients: ["Rice", "Moong Dal", "Turmeric", "Ghee"],
      }
    ]
  },
  {
    id: CategoryId.DRINKS,
    label: "Drinks",
    items: [
      {
        id: 'd1',
        name: "Sweet Lassi",
        description: "Thick, creamy yogurt drink topped with malai.",
        price: 80,
        image: "https://www.sharmispassions.com/wp-content/uploads/2023/08/sweet-lassi3.jpg",
        isPopular: true,
        isVeg: true,
        ingredients: ["Yogurt", "Sugar", "Cardamom", "Malai", "Dry Fruits"],
      },
      {
        id: 'd2',
        name: "Masala Chaas",
        description: "Spiced buttermilk.",
        price: 50,
        image: "https://t3.ftcdn.net/jpg/15/83/46/26/360_F_1583462634_K26J8L4OoOa3VTVlKGycKl9EmVgr7HVy.jpg",
        isVeg: true,
        ingredients: ["Yogurt", "Water", "Roasted Cumin", "Black Salt", "Coriander"],
      }
    ]
  }
];
